---
title: "Project 2 Visuals"
author: "Manou (CPSC 292-01)"
date: "12/9/2021"
output: html_document
---

```{r setup, include=TRUE}
library(ggplot2)
library(readxl)
library(xlsx)
```

```{r, include=TRUE}
manou_candy_data <- read_excel("manou-candy-data.xlsx")
manou_candy_data
```

```{r, include=TRUE}
ggplot(manou_candy_data, aes(x = averageprice, y = winpercent, fill = factor(caramel))) +
  geom_point(size = 2.5, shape =  21) +
  theme_minimal() +
  theme(legend.position = "bottom") +
  labs(main = "Does the Average Price of Caramel Candies Affect Win Percent?",x = "Average Price", y = "Win Percent", fill = "Caramel Presence (0 = F, 1 = T)")
```

conditional + function:
```{r, include=TRUE}

is_there_chocolate <- if(manou_candy_data$chocolate == 1) {
    print()
  }

is_there_chocolate_and_caramel <- function(a) {
  
}

```

Visual:
```{r, include=TRUE}

ggplot(manou_candy_data, aes(x = winpercent, y = averageprice)) +
  geom_point(size = 2.5, shape = 21) +
  geom_point() +
  geom_point() +
  theme_minimal() +
  labs(main = "Does the Average Price of Caramel Candies Affect Win Percent?",x = "Average Price", y = "Win Percent")

```

